env:
    browser: true
    es2021: true
extends:
    - plugin:react/recommended
    - airbnb
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 13
    sourceType: module
plugins:
    - react
rules:
    {
        "quotes": [2, "double"],
		"indent": 0,
		"react/jsx-indent": 0,
		"react/jsx-indent-props": 0,
		"comma-dangle": 0,
        "no-tabs": 0,
		"react/destructuring-assignment": 0,
		"react/prop-types": 0,
		"object-curly-newline": 0,
		"react/jsx-wrap-multilines": 0,
		"react/jsx-one-expression-per-line": 0,
		"react/no-unescaped-entities": 0,
        "react/function-component-definition": 0,
    }
